# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

addons:
  apt:
    packages:
      - libudunits2-dev
  homebrew:
    packages:
      - udunits

matrix:
  include:
    - os: linux
      r: devel
      env:
        - NOT_CRAN: true

    - os: linux
      r: release
      env:
        - NOT_CRAN: false

    - os: osx
      r: release
      env:
        - NOT_CRAN: false

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
